  <style>
  .fb-share-button
{
transform: scale(1.5);
-ms-transform: scale(1.5);
-webkit-transform: scale(1.5);
-o-transform: scale(1.5);
-moz-transform: scale(1.5);
transform-origin: top left;
-ms-transform-origin: top left;
-webkit-transform-origin: top left;
-moz-transform-origin: top left;
-webkit-transform-origin: top left;
}
</style>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.9&appId=1822789111305850";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- Section team -->
         <section id="team" class="team-section z-depth-1">
            <div class="sec-padded-1x">
                <div class="container">
                    <div class="row">
                        <div class="col s12 l8 offset-l2">
                            <div class="center-heading">
                                <h3 class="black-text">Prensa y comunidad </h3>
                                
                                <p class="black-text">Enterate de nuestras entrevistas, cosas relevantes y nuevos lanzamientos en esta sección.</p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <!--<div class="col s12 m6 l3">
                            <div class="card z-depth-2 wow fadeIn" data-wow-delay="0.1s">
                                <div class="card-image waves-effect waves-block waves-light">
                                </div>
                                <div class="card-content">
                                    <span class="card-title activator grey-text text-darken-4">Martin<i class="ion-android-more-vertical right"></i></span>
                                    <p>CEO</p>
                                    <ul class="list-inline list-follow">
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-facebook"></i></a></li>
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-twitter"></i></a></li>
                                        <li class="waves-effect"><a href="#" class="trans-effect"><i class="ion-social-linkedin"></i></a></li>
                                    </ul>
                                </div>
                                <div class="card-reveal">
                                    <span class="card-title grey-text text-darken-4">Martin<i class="ion-android-close right"></i></span>
                                    <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.</p>
                                </div>
                            </div>
                        </div>-->   
                        <div class="col s12 m6 l4">
                            <div class="card z-depth-2 wow fadeIn" data-wow-delay="0.2s">
                                <div class="card-image waves-effect waves-block waves-light">
                                    
                                    <iframe width="100%" height="240" src="https://www.youtube.com/embed/PFqr--WqFt8" frameborder="0" allowfullscreen></iframe>
                                </div>
                                <div class="card-content">
                                    <span class="card-title activator grey-text text-darken-4">¿Cómo nuestra funciona la App?<i class="ion-android-more-vertical right"></i></span>
                                    <p>app</p>
                                    <ul class="list-inline list-follow">
                                        <li class="waves-effect"><a href="https://business.facebook.com/Pegalinas/" target="_blank" class="trans-effect"><i class="ion-social-facebook"></i></a></li>
                                        <li class="waves-effect"><a href="https://twitter.com/pegalinas" target="_blank" class="trans-effect"><i class="ion-social-twitter"></i></a></li>
                                        <li class="waves-effect"><a href="https://www.youtube.com/channel/UCnzEiknp5FrTbw3zAUaNpjg" target="_blank" class="trans-effect"><i class="ion-social-youtube"></i></a></li>
                                    </ul>
                                </div>
                                <div class="card-reveal">
                                    <span class="card-title grey-text text-darken-4">RECUPERA <i class="ion-android-close right"></i></span>
                                    <p align=justify>Es la solución al problema de extravío de artículos y da un giro moderno a las etiquetas personalizadas a través de su plataforma digital.Recupera.net y la App Pegalinas Recupera para teléfonos inteligentes, es la forma más sencilla y efectiva de evitar que tanto los niños como los adultos pierdan definitivamente sus chamarras, pants, tenis, bolsas, libros y una infinidad de artículos tanto en la escuela como en el gimnasio y prácticamente en cualquier parte.</p>
                                </div>
                            </div>
                        </div>  
                        <div class="col s12 m6 l4">
                            <div class="card z-depth-2 wow fadeIn" data-wow-delay="0.3s">
                                <div class="card-image waves-effect waves-block waves-light">
                                     
                                    <iframe width="100%" height="240" src="https://www.youtube.com/embed/uFEtp4wk1Uc" frameborder="0" allowfullscreen></iframe>
                                </div>
                                <div class="card-content">
                                    <span class="card-title activator grey-text text-darken-4">Recupera tus Mascotas extraviadas<i class="ion-android-more-vertical right"></i></span>
                                    <p>Mi mascota</p>
                                    <ul class="list-inline list-follow">
                                        <li class="waves-effect"><a href="https://business.facebook.com/Pegalinas/" target="_blank" class="trans-effect"><i class="ion-social-facebook"></i></a></li>
                                        <li class="waves-effect"><a href="https://twitter.com/pegalinas" target="_blank" class="trans-effect"><i class="ion-social-twitter"></i></a></li>
                                        <li class="waves-effect"><a href="https://www.youtube.com/channel/UCnzEiknp5FrTbw3zAUaNpjg" target="_blank" class="trans-effect"><i class="ion-social-youtube"></i></a></li>
                                    </ul>
                                </div>
                                <div class="card-reveal">
                                    <span class="card-title grey-text text-darken-4">RECUPERA Mascotas<i class="ion-android-close right"></i></span>
                                    <p align=justify>Nuestra mascota es como si fuera un miembro de nuestra familia, ahora lo podemos localizar mas rapido y de forma segura con los tag de recupera. Solo hay que escanear el codigo para que llegue una notificacion y un correo electrónico a tu dispositivo movil con la ubicacion de donde se encuentra tu valiosa mascota.</p>
                                </div>
                            </div>
                        </div>     
                        <div class="col s12 m6 l4">
                            <div class="card z-depth-2 wow fadeIn" data-wow-delay="0.4s">
                                <div class="card-image waves-effect waves-block waves-light">                                
                                    <iframe width="100%" height="240" src="https://www.youtube.com/embed/MfRhRqSsEiM" frameborder="0" allowfullscreen></iframe>
                                </div>
                                <div class="card-content">
                                    <span class="card-title activator grey-text text-darken-4">¿Cómo aplicar las Pegalinas?  <i class="ion-android-more-vertical right"></i></span>
                                    <p>Ropa de Prueba</p>
                                    <ul class="list-inline list-follow">
                                        <li class="waves-effect"><a href="https://business.facebook.com/Pegalinas/" target="_blank" class="trans-effect"><i class="ion-social-facebook"></i></a></li>
                                        <li class="waves-effect"><a href="https://twitter.com/pegalinas" target="_blank" class="trans-effect"><i class="ion-social-twitter"></i></a></li>
                                        <li class="waves-effect"><a href="https://www.youtube.com/channel/UCnzEiknp5FrTbw3zAUaNpjg" target="_blank" class="trans-effect"><i class="ion-social-youtube"></i></a></li>
                                    </ul>
                                </div>
                                <div class="card-reveal">
                                    <span class="card-title grey-text text-darken-4">Ropa de Prueba<i class="ion-android-close right"></i></span>
                                    <p align=justify>Antes de aplicar una de las pegalinas de ropa planchables con tu nombre, vale la pena probar con las 2 Pegalinas de prueba que vienen dentro del paquete. Cada plancha funciona diferente y cuando no tienes práctica mas vale echar a perder!!!</p>
                                </div>
                            </div>
                        </div>  
                    </div>   
                </div>            
            </div>      
        </section> 