<!DOCTYPE html>
<html lang="en">

    <head>
    <style>
        .block_br {
    background: #2E9AFE none repeat scroll 0 0;
}

    hr { 
   border-top: 2px solid #03a9f4; 
   border-bottom: 2px solid #8cb400; 
   border-left:none; 
   border-right:none; 
   height: 6px; 
 } 
    </style>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Stylesheet -->
       <!-- <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,100,400italic,500,300italic,500italic,700,700italic' rel='stylesheet' type='text/css'>
        <link href="css/materialize.min.css" rel="stylesheet">
        <link href="css/slider.css" rel="stylesheet" type="text/css">
        <link href="css/animate.css" rel="stylesheet" type="text/css">
        <link href="css/ionicons.min.css" rel="stylesheet" type="text/css">
        <link href="css/style.css" rel="stylesheet" type="text/css">
        <script src="js/modernizr.custom.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js"></script>

         Favicons -->
        <!-- <link rel="apple-touch-icon-precomposed" sizes="57x57" href="img/icons/favicons/57px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/icons/favicons/114px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/icons/favicons/72px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/icons/favicons/114px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="60x60" href="img/icons/favicons/60px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="120x120" href="img/icons/favicons/120px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="76x76" href="img/icons/favicons/76px.png" />
        <link rel="apple-touch-icon-precomposed" sizes="152x152" href="img/icons/favicons/152px.png" />
        <link rel="icon" type="image/x-icon" href="img/icons/favicons/32px.png" />
        <link rel="icon" type="image/png" href="img/icons/favicons/196px.png" sizes="196x196" />
        <link rel="icon" type="image/png" href="img/icons/favicons/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/png" href="img/icons/favicons/32px.png" sizes="32x32" />
        <link rel="icon" type="image/png" href="img/icons/favicons/16px.png" sizes="16x16" />
        <link rel="icon" type="image/png" href="img/icons/favicons/favicon-128.png" sizes="128x128" />-->

     <link href="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.css'); ?>" rel="stylesheet" type="text/css" media="screen" >

     <script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.js'); ?>"></script>
     <script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/localization/validettaLang-es-ES.js'); ?>"></script>
        <meta name="application-name" content="Volkan"/>

        <!-- Title -->
        <title>Recupera by Pegalinas</title> 

    </head>

    <body>
    <br>
    <br><br>
    <br>

		<section id="faqs" class="faqs-section sec-padded-1x z-depth-1">
            <div class="container">
                <div class="row">
                    
                    <div class="col s12 m12 l12">
                        <div class="center-heading">
                            <h3 class="black-text">Preguntas más frecuentes</h3>               
                        </div>
                        <ul class="collapsible z-depth-2" data-collapsible="accordion">
                           
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿POR QUÉ DEBO REALIZAR SIMULACROS?</div>
                                <div class="collapsible-body"><p>Los simulacros enseñan a reaccionar ante sucesos peligrosos; así es como la App de Voluntario nos motiva a tomar las precauciones necesarias para estar a salvo.<br>
                                      </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿LA APP DE VOLUNTARIO PUEDE NOTIFACARME CUANDO OCURRE UN SISMO?</div>
                                <div class="collapsible-body"><p>No. Voluntario solo es una app que permite a cualquier usuario organizar simulacros individuales, familiares, grupales y masivos con el fin de crear una culrura de prevención en la población mexicana.</p></div>
                            </li>
                            
                             <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>
                                ¿QUÉ ES UN SIMULACRO DE EMERGENCIA?
                                </div>
                                <div class="collapsible-body"><p>
                                Es una simulación de una situación de emergencia, donde se recrean las dificultades reales, es
                                el mejor medio de verificar el mantenimiento de las instalaciones, examinar las actuaciones de
                                salvamento y evacuación, tiempos y protocolos internos que se aplican.
                                </p></div>
                             </li>
                             
                             <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>
                                ¿QUIÉN DEBE REALIZAR EL SIMULACRO DE EMERGENCIA? 
                                </div>
                                <div class="collapsible-body"><p>
                                Todo el personal de la empresa, trabajador/es designados para rescate y auxilio, y puede asistir
                            	un técnico del Servicio de Prevención Ajeno contratado, si es el caso. 
                                </p></div>
                             </li>
                            
                            
                             <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>
                                ¿CADA CUÁNTO TIEMPO SE DEBE REALIZAR EL SIMULACRO DE EMERGENCIA? 
                                </div>
                                <div class="collapsible-body"><p>
                                Se deberá realizar un simulacro de emergencia, al menos una vez al año, sin embargo este
                            	tiempo puede ser menor si así es decidido por la organización o cualquier persona. 
                                </p></div>
                             </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿Y SI NO RECUERDO MI CONTRASEÑA?</div>
                                <div class="collapsible-body"><p>No te preocupes, también puedes recuperarla :) Solo tendrás que hacer clic en “¿Olvidaste tu contraseña?” indicarnos la dirección de email con la que te registraste en WWW.RECUPERA.NET y te enviaremos un enlace vía email desde el que podrás cambiar la contraseña por una nueva y acceder a tu cuenta de nuevo.</p></div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿PUEDO MODIFICAR LOS DATOS DE MI CUENTA EN VOLUNTARIO?</div>
                                <div class="collapsible-body"><p>
                               Si. Desde tu Perfil de usuario podrás cambiar tus datos personales y datos de contacto 
                                    </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿PARA QUÉ NECESITAN MIS DATOS PERSONALES?</div>
                                <div class="collapsible-body"><p>
                               Se necesitan para el estricto funcionamiento del servicio de recuperación de objetos perdidos. 
                                    </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿CUÁNTO CUESTA EL USO DE LA PLATAFORMA Y APP RECUPERA?</div>
                                <div class="collapsible-body"><p>
                               No tiene costo. ¡Sólo necesitas adquirir las Pegalinas RECUPERA para tener acceso a todos los beneficios!
                                    </p>
                                </div>
                            </li>

                        </ul>
                    </div> <!--Col ends -->
                </div> <!--Row ends-->
            </div> <!--Container ends -->
        </section> <!--Section ends -->
       
        <script src="js/materialize.min.js" type="text/javascript"></script>
        <script src="js/jquery.smoothscroll.min.js" type="text/javascript"></script>
        <script src="js/typed.min.js" type="text/javascript"></script>
        <script src="js/wow.min.js" type="text/javascript"></script>
        <script src="js/waypoint.min..js" type="text/javascript"></script>
        <script src="js/jquery.counterup.min.js" type="text/javascript"></script>
        <script src="js/owl.carousel.min.js" type="text/javascript"></script>
        <script src="js/jquery.flexslider-min.js" type="text/javascript"></script>
        <script src="js/jquery.validate.js" type="text/javascript"></script>
        <script src="js/classie.js" type="text/javascript"></script>
        <script src="js/config.js" type="text/javascript"></script>
       


    </body>

</html>