    
    <style>
  .fb-share-button
{
transform: scale(1.5);
-ms-transform: scale(1.5);
-webkit-transform: scale(1.5);
-o-transform: scale(1.5);
-moz-transform: scale(1.5);
transform-origin: top left;
-ms-transform-origin: top left;
-webkit-transform-origin: top left;
-moz-transform-origin: top left;
-webkit-transform-origin: top left;
}
</style>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.9&appId=1822789111305850";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
    <br>
    <br><br>
    <br>

		<section id="faqs" class="faqs-section sec-padded-1x z-depth-1">
            <div class="container">
                <div class="row">
                    
                    <div class="col s12 m12 l12">
                        <div class="center-heading">
                            <h3 class="black-text">Preguntas más frecuentes</h3>               
                        </div>
                        <ul class="collapsible z-depth-2" data-collapsible="accordion">
                            <li>
                                <div class="collapsible-header active"><i class="ion-android-more-vertical"></i>¿Cómo funciona el sistema de protección de Recupera Mascota?</div>
                                <div class="collapsible-body"><p>Crea tu cuenta, escanea y activa el Tag y completa el perfil de tu mascota en la App Recupera o en Recupera.pet. El perfil contiene información sobre tu mascota incluyendo su foto, nombre, raza, edad, etc.<br><br>

                                 Cuando el código QR del TAG se escanea con un smartphone, la persona que encuentra tu mascota  la información del perfil  de tu mascota<br>
	                              </p></div>
                            </li>
                            <li>
                                <div class="collapsible-header active"><i class="ion-android-more-vertical"></i>En el registro de una cuenta nueva, me pide registrar un PIN para recoger artículos. ¿Qué es esto?</div>
                                <div class="collapsible-body"><p>Dado que la cuenta funciona tanto para dar de alta mascotas como artículos varios con el uso de Pegalinas Recupera, ese PIN sirve cuando un objeto es perdido por ejemplo en un colegio o gimnasio, y al ir a recoger el artículo el sistema pide dicho PIN para validar que se le está devolviendo al verdadero dueño. Para el caso de mascotas, no se usa realmente, pero forma parte de la plataforma.<br>
                                  </p></div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿Qué sucede cuando se extravía mi mascota?</div>
                                <div class="collapsible-body"><p>Si es encontrada por una persona y detecta que trae un Tag Recupera, con su Smartphone y alguna aplicación gratuita para leer códigos QR, escaneará el código QR que viene al reverso del Tag, para iniciar el proceso de devolución al abrirse una hoja de contacto a donde escribirá su nombre, teléfono y correo electrónico para que lo contactes.<br>

                                      Si no tiene un smartphone, en el Tag se indica que podrá capturar el Folio que viene en el Tag directamente en la página web Recupera.pet<br>
                                      </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿Al cambiar el estado de mi mascota a “Extraviado”, ¿qué sucede?</div>
                                <div class="collapsible-body"><p>Se te despliega una opción para que puedas compartir los datos básicos de tu mascota (nombre, fotografía y monto de recompensa) con tus contactos en redes sociales.</p></div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿La persona que encuentra la mascota y escanea el Tag, tiene que tener instalada la App de Recupera?</div>
                                <div class="collapsible-body"><p>No. Podrá hacerlo con cualquier App gratuita de lector de códigos QR disponible en las tiendas de Aplicaciones o la que viene por defecto en la cámara de muchos smartphones.</p></div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿Qué sucede una vez que el Tag fue escaneado?</div>
                                <div class="collapsible-body"><p>

                                    Recibirás una notificación por correo electrónico y una alerta a tu celular, indicando que se ha escaneado el Tag de su mascota y con la ubicación (siempre que tenga activada los permisos de localización en su celular) a donde se escaneó el código y los datos de contacto de la persona <br>

                                    </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿Puedo añadir el nombre y el número de teléfono de mi mascota al Tag para que sea visible?</div>
                                <div class="collapsible-body"><p>
                                	Por el momento no, pero el código QR ya contiene toda esa información en el perfil de la mascota

                                </p>
                                </div>
                            </li>                            
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿Qué viene con la compra del Tag?</div>
                                <div class="collapsible-body"><p>Incluye:<br>
                                •   La App gratuita Pegalinas Recupera, para descargarse gratis al smartphone y con acceso también vía la página de Recupera.net<br>
                                •   Almacenamiento de la información de tu mascota: agrega toda la información de contacto de tu mascota en su perfil en línea

                                    </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿Hay una cuota mensual una vez que he pagado por el Tag?</div>
                                <div class="collapsible-body"><p>
                                No hay una cuotas ni cargos ocultos, así de simple
                                    </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿Puedo actualizar la información de mi mascota?</div>
                                <div class="collapsible-body"><p>
                                Sí. En cualquier momento puedes hacerlo, con sólo entrar a tu cuenta de Recupera y al perfil que creaste de tu mascota.
                                    </p>
                                </div>
                            </li>
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿Cómo funciona la función GPS? ¿Puedo activamente localizar a mi mascota?</div>
                                <div class="collapsible-body"><p>
                               La función GPS es una búsqueda "pasiva" mediante software incorporado en el dispositivo móvil de la persona que ha escaneado el Tag. Cuando se escanea el código QR, el sistema determina que procede de un dispositivo móvil (como un smartphone o una tableta con conexión a internet) y envía una alerta al celular al propietario de la mascota con el mapa GPS de la ubicación donde se realizó la lectura del código.
                                    </p>
                                </div>
                            </li>
                           
                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿Tengo que reemplazar el Tag de mi mascota cada año?</div>
                                <div class="collapsible-body"><p>
                               No, nuestros Tags son duraderos; sin embargo, si por alguna circunstancia el Tag se dañara por algún golpe, mordida, etc., puedes adquirir un nuevo Tag y vincularlo al perfil de tu mascota tal como lo hizo antes (visita nuestra tienda en línea). 
                                    </p>
                                </div>
                            </li>

                            <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿La App de Recupera funciona sólo con algún tipo o marca de teléfono inteligente?</div>
                                <div class="collapsible-body"><p>
                               Nuestra App funciona con cualquier marca de teléfono y cualquier sistema operativo (IOS y Android). Puede utilizar cualquier lector de código QR que elija. Esto es útil por lo que si un rescatista encuentra a su mascota que sólo puede utilizar lo que tienen y no necesita descargar nada más.
                                    </p>
                                </div>
                            </li>
                             <li>
                                <div class="collapsible-header"><i class="ion-android-more-vertical"></i>¿Tienes más preguntas?, ¡Contáctanos! </div>
                                <div class="collapsible-body"><p> Contacta al equipo de Recupera para solucionar todas tus dudas.
                                
                                    </p>
                                </div>
                            </li>

                        </ul>
                    </div> <!--Col ends -->
                </div> <!--Row ends-->
            </div> <!--Container ends -->
        </section> <!--Section ends -->


    </script>
  