<div class="row" style="margin-top: 20px;">
	<div class="col s12 m6 offset-m3 l4 offset-l4">

		<div class="card">
			<div class="card-content">
				<form>
					<div class="row">
						<div class="col s12 m12 l12 center">
    						<img class="responsive-img" src="http://mediaa.pegalinas.com/img/new-store-logo-1451194128.jpg" alt="logo-pegalinas">
						</div>
					</div>
					<div class="row">
						<div class="col s12 m12 l12">
							<!--<p class="center-align grey-text text-darken-3">Hacer tu vida más fácil es nuestra meta, ver a tu familia feliz, nuestra recompensa.</p>-->
						</div>
					</div>
					<div class="row">
						<div class="input-field col s12 m12 l12">
							<i class="material-icons prefix">perm_identity</i>
		          			<input id="name_user" type="text" class="validate">
		          			<label for="name_user">Nombre</label>
		        		</div>
					</div>
					<div class="row">
						<div class="input-field col s12 m12 l12">
							<i class="material-icons prefix">email</i>
		          			<input id="email_user" type="email" class="validate">
		          			<label for="email_user">Correo electr&oacute;nico</label>
		        		</div>
					</div>
					<div class="row">
						<div class="input-field col s12 m12 l12">
							<i class="material-icons prefix">lock</i>
		          			<input id="password_user" type="password" class="validate">
		          			<label for="password_user">Contrase&ntilde;a</label>
		        		</div>
					</div>
					<div class="row">
						<div class="input-field col s12 m12 l12">
							<i class="material-icons prefix">lock</i>
		          			<input id="repeat_password_user" type="password" class="validate">
		          			<label for="repeat_password_user">Repetir Contrase&ntilde;a</label>
		        		</div>
					</div>
					<div class="row">
						<div class="col s12 m12 l12">
							<a class="waves-effect waves-light btn blue col s12 m12 l12">Reg&iacute;strate ahora</a>
						</div>
					</div>
					<div class="row">
						<div class="col s12 m12 l12">
							<p class="center-align">
								¿Ya tienes una cuenta?
								<a href="<?php echo $this->basePath('/auth'); ?>">Iniciar sesi&oacute;n</a>
							</p>
						</div>
					</div>
				</form>
			</div>
		</div>

	</div>
</div>