<h1>Articulos</h1>
<?php 
$flash=$this->flashMessenger()
            ->setMessageOpenFormat('<div%s>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</div>');
?>
<table class="table">
    <tr>
        <td colspan="7">
            <a class="btn btn-success" href="<?=$this->basePath()?>/articulo/add">Añadir usuario</a> 
              <?php echo $flash->render('add_correcto',array('btn', 'btn-success'));?>
              <?php echo $flash->render('eliminado',array('btn', 'btn-success'));?>
              
        </td>
    </tr>
    <tr>
        <th>ID</th>
        <th>Sector</th>
    </tr>
    <?php foreach($tipoArticulo as $tipo){ ?>
    <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
        <td><?=$tipo["id"]?></td>
        <td><?=$tipo["type"]?></td>
        <td><a class="btn btn-primary" href="<?=$this->basePath()?>/articulo/modificar/<?=$tipo["id"]?>">Modificar</a></td>
        <td><a class="btn btn-danger" href="<?=$this->basePath()?>/articulo/eliminar/<?=$tipo["id"]?>">Eliminar</a></td>
        
    </tr>
    <?php } ?>
</table>