 <style>
.circle-icon .material-icons {
	position: absolute;
	margin-top: -58px;
	margin-left: -46px;
	background-color: #009688;
	color: white;
	padding: 8px;
	font-size: 3em;
	/*border-radius: 50%; */
	transform: rotate(15deg);
}
.container_img_art img {
    /*width: 150px;
    height: 150px;*/
    /*border-radius: 150px;*/
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 20px;
    margin-top: 10px;
    /*border: 4px solid #ccc;*/
}
</style>

<div class="row">

	<div class="col s12 m12 l12" style="margin-bottom: 35px;">
		<h3 class="grey-text text-darken-2 text-architects-daughter">Detalle de la mascota</h3>
	</div>

	<div class="col s12 m12 l12" style="margin-bottom: 60px;">
		<a class="waves-effect waves-light btn-large orange tooltipped" data-position="bottom" data-delay="50" data-tooltip="Regresar" href="<?php echo $this->basePath('/pets'); ?>">
			<i class="material-icons left">replay</i> Regresar
		</a>
	</div>

	<div class="col s12 m12 l12">
		<div class="card-panel">

			
			<div class='circle-icon'>
				<i class="material-icons">description</i>
			</div>

			<div class="row"> 

				<div class="col s12 m12 l12"><br>
					<h4 class="grey-text text-darken-2 center-align"><?php echo "Mascota: " . $this->pet["name_pet"]; ?></h4>
				</div>

			</div>

			<div class="row">
				
				<div class="col s12 m12 l12 center container_img_art">
					<?php
					$imagenDefault = $this->basePath('img/icon_pet_real.png');

					$imagenFull = '';

					if ($this->pet["image_name"] != '') {
						$imagenFull = $this->basePath('images/pets/'.$this->pet["image_name"]);
					} else {
						$imagenFull = $imagenDefault;
					}
					?>
					<img class="z-depth-2 materialboxed responsive-img" src="<?php echo $imagenFull; ?>" alt="mascota" style="height: 300px; width: auto;" />
				</div>

			</div>

			<div class="row">

				<div class="col s12 m3 l3">
					<h5 class="grey-text">Tipo:</h5>
				</div>

				<div class="col s12 m9 l9">
					<h5 class="grey-text">
						<?php
						switch($pet["type_pet"]) {
							case 1 :
								echo "Perro";
								break;
							case 2 :
								echo "Gato";
								break;
							case 3 :
								echo "Otro";
								break;
							default :
								echo "Desconocido";
								break;
						}
						?>
					</h5>
				</div>
				
			</div>

			<div class="row">

				<div class="col s12 m3 l3">
					<h5 class="grey-text">Raza:</h5>
				</div>

				<div class="col s12 m9 l9">
					<h5 class="grey-text"><?php echo $this->pet["breed_pet"]; ?></h5>
				</div>
				
			</div>

			<div class="row">

				<div class="col s12 m3 l3">
					<h5 class="grey-text">Tama&ntilde;o:</h5>
				</div>

				<div class="col s12 m9 l9">
					<h5 class="grey-text">
					<?php
						switch($pet["size_pet"]) {
							case 1 :
								echo "Chica";
								break;
							case 2 :
								echo "Mediana";
								break;
							case 3 :
								echo "Grande";
								break;
							case 4 :
								echo "Gigante";
								break;
							default :
								echo "Desconocido";
								break;
						}
					?>
					</h5>
				</div>
				
			</div>
			 
			<div class="row">

				<div class="col s12 m3 l3">
					<h5 class="grey-text">Color:</h5>
				</div>

				<div class="col s12 m9 l9">
					<h5 class="grey-text"><?php echo $this->pet["color_pet"]; ?></h5>
				</div>
				
			</div>

			<div class="row">

				<div class="col s12 m3 l3">
					<h5 class="grey-text">Edad:</h5>
				</div>

				<div class="col s12 m9 l9">
					<h5 class="grey-text"><?php echo $this->pet["age_pet"]; ?></h5>
				</div>
				
			</div>

			<div class="row">

				<div class="col s12 m3 l3">
					<h5 class="grey-text">Peso:</h5>
				</div>

				<div class="col s12 m9 l9">
					<h5 class="grey-text"><?php echo $this->pet["weight"]; ?></h5>
				</div>
				
			</div>

			<div class="row">

				<div class="col s12 m3 l3">
					<h5 class="grey-text">Cumplea&ntilde;os:</h5>
				</div>

				<div class="col s12 m9 l9">
					<h5 class="grey-text"><?php echo $this->pet["birthday_pet"]; ?></h5>
				</div>
				
			</div>

			<div class="row">

				<div class="col s12 m3 l3">
					<h5 class="grey-text">N° de microchip:</h5>
				</div>

				<div class="col s12 m9 l9">
					<h5 class="grey-text"><?php echo $this->pet["microchip_pet"]; ?></h5>
				</div>
				
			</div>

			<div class="row">

				<div class="col s12 m3 l3">
					<h5 class="grey-text">Nombre de veterinario:</h5>
				</div>

				<div class="col s12 m9 l9">
					<h5 class="grey-text"><?php echo $this->pet["name_vet"]; ?></h5>
				</div>
				
			</div>

			<div class="row">

				<div class="col s12 m3 l3">
					<h5 class="grey-text">Tel&eacute;fono de veterinario:</h5>
				</div>

				<div class="col s12 m9 l9">
					<h5 class="grey-text"><?php echo $this->pet["phone_vet"]; ?></h5>
				</div>
				
			</div>

			<div class="row">

				<div class="col s12 m3 l3">
					<h5 class="grey-text"> Recompensa $: </h5>
				</div>

				<div class="col s12 m9 l9">
					<h5 class="grey-text"><?php echo $this->pet["reward"]; ?></h5>
				</div>
				
			</div>

			<div class="row">

				<div class="col s12 m3 l3">
					<h5 class="grey-text">Descripci&oacute;n:</h5>
				</div>

				<div class="col s12 m9 l9">
					<h5 class="grey-text"><?php echo $this->pet["description_pet"]; ?></h5>
				</div>
				
			</div>

		</div>

	</div>

</div>

<script>
	
$(document).ready(function(){
	$('.materialboxed').materialbox();
});
        
</script>