<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">

<script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->basePath('/pegalinaslive/jquery-loading-overlay-master/src/loadingoverlay.min.js'); ?>"></script>

<div class="row">
	
	<div class="col s12 m12 l12">
		<h3 class="grey-text text-darken-2 text-architects-daughter">Mis mascotas</h3><br>
	</div>

	<div class="col s12 m6 l6" style="margin-bottom: 20px;">

		<a class="waves-effect waves-light btn-large   pink darken-1 tooltipped" data-position="bottom" data-delay="50" data-tooltip="Agregar Mascota" href="<?php echo $this->basePath('/pets/add'); ?>">
			<i class="material-icons left">add_circle</i> Registrar nueva mascota
		</a>

	</div>

	<div class="col s12 m12 l12">
	
		<table id="table_pets" class="bordered striped highlight responsive-table">

			<thead>
				<tr>
					<th data-field="imgArt">Foto</th>
					<th data-field="id">Tipo</th>
					<th data-field="category">Raza</th>
					<th data-field="nombre">Nombre</th>
					<th data-field="color">Tama&ntilde;o</th>
					<th data-field="marca">Color</th>
					<th data-field="status">Estatus</th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>

			<tbody>
			<?php foreach($this->pets as $pet) : ?>
				<tr>
					<td>
					<?php if($pet["image_name"] != '' && $pet["image_name"] != null) :  ?>
						<img style="width: 50px; height: 50px" src="<?php echo $this->basePath('images/pets/' . $pet["image_name"]); ?>" alt="mascota">
					<?php else : ?>
						<img style="width: 50px; height: 50px" src="<?php echo $this->basePath('img/icon_pet_real.png'); ?>" alt="mascota">
					<?php endif; ?>
					</td>
					<td>
						<p class="truncate">
						<?php
						switch($pet["type_pet"]) {
							case 1 :
								echo "Perro";
								break;
							case 2 :
								echo "Gato";
								break;
							case 3 :
								echo "Otro";
								break;
							default :
								echo "Desconocido";
								break;
						}
						?>
						</p>
					</td>
					<td><?php echo $pet["breed_pet"]; ?></td>
					<td><?php
					echo $pet["name_pet"];
					?></td>
					<td>
					<?php
						switch($pet["size_pet"]) {
							case 1 :
								echo "Chica";
								break;
							case 2 :
								echo "Mediana";
								break;
							case 3 :
								echo "Grande";
								break;
							case 4 :
								echo "Gigante";
								break;
							default :
								echo "Desconocido";
								break;
						}
					?>
					</td>
					<td><?php echo $pet["color_pet"]; ?></td>
					<td>

						<?php
							switch ($pet["name_status"]) {
								case 'Asignado':
									$color = 'teal';
									break;
								case 'Prestado':
									$color = 'blue';
									break;
								case 'Extraviado':
									$color = 'red';
									break;
								default:
									$color = 'green';
									break;
							}
						?>
						
						<select name="id_status" class="id_status" data-idpet="<?php echo $pet['id']; ?>" data-codeqr="<?php echo $pet['id_register_qr']; ?>">
     	 					<option value="2" <?php echo ($pet['id_status'] == 2) ? 'selected' : '' ?>>Registrado</option>
      						<!--<option value="3" <?php //echo ($pet['id_status'] == 3) ? 'selected' : '' ?>>Prestado</option>-->
      						<option value="4" <?php echo ($pet['id_status'] == 4) ? 'selected' : '' ?>>Extraviado</option>
							<option value="6" disabled <?php echo ($pet['id_status'] == 6) ? 'selected' : '' ?>>Devuelto</option>
							<option value="7" disabled <?php echo ($pet['id_status'] == 7) ? 'selected' : '' ?>>Encontrado</option>
    					</select>
					</td>
					<td class="center">
						<a class="waves-effect waves-light btn-floating teal tooltipped" data-position="left" data-delay="50" data-tooltip="Detalle Mascota" href="<?php echo $this->basePath('/pets/detail/') . $pet["id"]; ?>">				
      						<i class="material-icons">description</i>
						</a>
					</td>
					<td class="center">
						<a class="waves-effect waves-light btn-floating blue tooltipped" data-position="left" data-delay="50" data-tooltip="Editar Mascota" href="<?php echo $this->basePath('/pets/edit/') . $pet["id"]; ?>">				
      						<i class="material-icons">mode_edit</i>
						</a>
					</td>
					<td class="center">
						<a class="waves-effect waves-light btn-floating red tooltipped" data-position="left" data-delay="50" data-tooltip="Eliminar Mascota" href="<?php echo $this->basePath('/pets/delete/') . $pet["id_register_qr"]; ?>">
							<i class="material-icons">delete</i>
						</a>
					</td>
					<td class="center">
						<a class="waves-effect waves-light btn-floating amber tooltipped" data-position="left" data-delay="50" data-tooltip="Ver Mapa" href="<?php echo $this->basePath('/pets/see-map/') . $pet["id"]; ?>" >
							<i class="material-icons">location_on</i>
						</a>
					</td>
					
				</tr>
			<?php endforeach; ?>
			</tbody>

		</table>

	</div>

</div>

<script>

	// BasePath
	var $basePath = '<?php echo $this->basePath(); ?>';

	// Combo estatus
	var $select_status = $(".id_status");

	// ***********************************************************************
	// EVENTOS QUE SE EJECUTAN CUANDO INICIA UN AJAX Y CUANDO TERMINA
	// ***********************************************************************
	$(document)
		.ajaxStart(function () {
			//console.log("Inicia Ajax");
			// Iniciamos panel de carga
			$.LoadingOverlay("show");
		})
		.ajaxStop(function () {
			//console.log("Termina Ajax");
			// ocultamos panel de carga
			$.LoadingOverlay("hide");
		});

	$('select').material_select();

	// ***********************************************************************
	// Cuando el documento esta listo
	// ***********************************************************************
	$(document).ready(function() {

		$('.materialboxed').materialbox();

		// Inicializar modales
		$('.modal').modal({
			dismissible: false
		});


    	$('#table_pets').DataTable({
      		"language": {
            	"sProcessing":     "Procesando...",
            	"sLengthMenu":     "Mostrar _MENU_ registros",
            	"sZeroRecords":    "No se encontraron resultados",
            	"sEmptyTable":     "Ningún dato disponible en esta tabla",
            	"sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            	"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
            	"sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
            	"sInfoPostFix":    "",
            	"sSearch":         "Buscar:",
            	"sUrl":            "",
            	"sInfoThousands":  ",",
            	"sLoadingRecords": "Cargando...",
            	"oPaginate": {
            	    "sFirst":    "Primero",
            	    "sLast":     "Último",
            	    "sNext":     "Siguiente",
            	    "sPrevious": "Anterior"
            	},
            	"oAria": {
            	    "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
            	    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
            	}
			},
			"columnDefs" : [{
      			"targets": [ 7, 8, 9, 10 ],
      			"orderable": false
    		}]
	    });

	    $("#table_pets_length select").val('10'); //seleccionar valor por defecto del select
		$('#table_pets_length select').addClass("browser-default"); //agregar una clase de materializecss de esta forma ya no se pierde el select de numero de registros.
		//$('select').material_select(); //inicializar el select de materialize

		// Cambio en el combo status
		$select_status.on('change', function(event) {
			event.preventDefault();
			
			// Valor del combo
			var statusPet = $(this).val();

			var $dataCodeQR   = $(this).data('codeqr');

			var $dataIPet   = $(this).data('idpet');
			//alert($dataCodeQR); fvxe;

				swal({
				  title: '¿Estás seguro?',
				  text: "Actualizaras el estatus de tu mascota!",
				  type: 'warning',
				  showCancelButton: true,
				  confirmButtonColor: '#3085d6',
				  cancelButtonColor: '#d33',
				  confirmButtonText: 'Aceptar',
				  cancelButtonText: 'Cancelar',
				  //confirmButtonClass: 'btn btn-success',
				  //cancelButtonClass: 'btn btn-danger',
				  //buttonsStyling: false
				}).then(function () {
					$.ajax({
		        			url: $basePath + '/pets/updatestatus',
		        			type: 'POST',
		        			dataType: 'json',
		        			data: {id : $dataCodeQR, id_status: statusPet }
					})
					.done(function(response) {
		        			console.log(response);
		        			//console.log("success");
		        			if (response.status == 'ok') {
		        				Materialize.toast('Estatus actualizado!', 3000);
		        			} else if(response.status == 'fail'){
		        				swal(
				  					'Opsss..',
				  					'¡Ocurrio un error intentalo de nuevo!',
				  					'error'
								);
		        			}

					})
					.fail(function() {
						console.log("error");
					})
					.always(function() {
						console.log("complete");
					});
				}, function (dismiss) {
					// dismiss can be 'cancel', 'overlay',
					// 'close', and 'timer'
					if (dismiss === 'cancel') {
				    	swal(
					      	'Cancelado',
					      	'No actualizaste el estatus de tu mascota',
					      	'error'
				    	)
					}
				});

		});

	} );
</script>