<link href="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.css'); ?>" rel="stylesheet" type="text/css" media="screen" >
<link rel="stylesheet" href="<?php echo $this->basePath('/pegalinaslive/css/paw_dog.css'); ?>">

<script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/dist/validetta.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/pegalinaslive/validetta-1.0.1/localization/validettaLang-es-ES.js'); ?>"></script>
<script src="<?php echo $this->basePath('/pegalinaslive/jquery-loading-overlay-master/src/loadingoverlay.min.js'); ?>"></script>

<script src='https://www.google.com/recaptcha/api.js'></script>

<style>
	.input-field .prefix ~ .select-wrapper {
	  margin-left:3rem; 
	  width:92%; 
	  width:calc(100% - 3rem);
	}
	.background-image-pet {
		background-color: transparent;
		background-image: url(https://images.pexels.com/photos/46024/pexels-photo-46024.jpeg?w=1260&h=750&dpr=2&auto=compress&cs=tinysrgb) ;
		background-position: center center;
		background-repeat: no-repeat;
		background-attachment: initial;
		background-size: cover;
	}
	.container-background-image-pet {
		background-color: rgba(0,0,0,0.3);
	}

	.targetOuter {	
		position :relative;
	    text-align : center;
	    background-color : #ffebee ;
	    margin : 20px auto;
	    width : 200px;
	    height : 200px;
		border-radius : 4px;
	}
	.icon-choose-image {
	    position : absolute;
	    opacity : 0.1;
	    top : 50%;
	    left : 50%;
	    margin-top : -24px;
	    margin-left : -24px;
	    width : 48px;
	    height : 48px;
	}
	.inputFile {
	    padding : 5px 0px;
		margin-top :8px;	
	    background-color : #FFFFFF;
	    width : 48px;	
	    overflow : hidden;
		opacity : 0;	
		cursor :pointer;
	}
</style>

<div class="row" style="margin-top: 130px; margin-bottom: 50px;">
	<div class="col s12 m8 offset-m2 l8 offset-l2">

		<div class="card background-image-pet">

			<div class="dog">
				<div class="pad"></div>
			    <div class="toe-1"></div>
			    <div class="toe-2"></div>
			    <div class="toe-3"></div>
			    <div class="toe-4"></div>
			</div>

			<div class="card-content container-background-image-pet">

				<div class="row">
					<div class="col s12 m12 l12 center">
						<img class="responsive-img" src="<?php echo $this->basePath('/img/pets/logorecuperamascotaoutline.png') ?>" alt="logo-pegalinas" style="height: 150px;" />
					</div>
				</div>

				<div class="row">
					<div class="col s12 m12 l12 center">
						<h6 class="white-text text-darken-4">Recupera pet, el camino m&aacute;s corto entre tu mascota perdida y t&uacute;</h6>
					</div>
				</div>
				
			</div>
			
		</div>

		<?php
		$form = $this->form;
		$form->prepare();
		echo $this->form()->openTag($form);
		echo $this->formElement($form->get('id'));
		?>

		<div id="container-data-sign" class="card" style="border-top-width: 3px; border-top-color: #D41C76; border-top-style: solid; display: block;">
			<div class="card-content">
				
				<div class="row">
					<div class="col s12 m12 l12">
						<h5 class="center">Datos de acceso</h5>
					</div>
				</div>

				<input type="text" id="type_user" name="type_user" placeholder="type user" style="display: none;" value="3" />

				<div class="row">
					
					<div class="input-field col s12 m12 l6">
						<i class="material-icons prefix">email</i>
		          		<?php echo $this->formElement($form->get('email_user')); ?>
		          		<label for="email_user">Correo electr&oacute;nico</label>
		        	</div>

		        	<div class="input-field col s12 m12 l6">
						<i class="material-icons prefix">email</i>
		          		<?php echo $this->formElement($form->get('repeat_email_user')); ?>
		          		<label for="repeat_email_user">Repetir Correo electr&oacute;nico</label>
		        	</div>

				</div>

				<div class="row">

					<div class="input-field col s12 m12 l6">
						<i class="material-icons prefix">lock</i>
		          		<?php echo $this->formElement($form->get('password_user')); ?>
		          		<label for="password_user">Contrase&ntilde;a</label>
		        	</div>

					<div class="input-field col s12 m12 l6">
						<i class="material-icons prefix">lock</i>
						<?php echo $this->formElement($form->get('repeat_password_user')); ?>
		          		<label for="repeat_password_user">Repetir Contrase&ntilde;a</label>
		        	</div>

				</div>

			</div>
		</div>

		<div id="container-data-contact-personal" class="card" style="border-top-width: 3px; border-top-color: #D41C76; border-top-style: solid; display: block;">
			<div class="card-content">

				<div class="row">
					<div class="col s12 m12 l12">
						<h5 class="center title-data-contact-personal">Datos de contacto</h5>
					</div>
				</div>
				
				<div class="row">

					<div class="input-field col s12 m12 l6">
						<i class="material-icons prefix">perm_identity</i>
		          		<?php echo $this->formElement($form->get('name_user')); ?>
		          		<label id="label_name_user" for="name_user">Nombre</label>
		        	</div>

		        	<div id="container_surname">
						<div class="input-field col s12 m12 l6">
							<i class="material-icons prefix">perm_identity</i>
			       			<?php echo $this->formElement($form->get('surname')); ?>
			        		<label for="surname">Apellido paterno</label>
			        	</div>
					</div>

				</div>

				<div class="row">

					<div class="input-field col s12 m12 l6">
						<i class="material-icons prefix">phone</i>
			          	<?php echo $this->formElement($form->get('phone')); ?>
			          	<label for="phone">Tel&eacute;fono </label>
			        </div>

					<div id="container_website">
						<div class="input-field col s12 m12 l6">
							<i class="material-icons prefix">web</i>
			        		<?php echo $this->formElement($form->get('website')); ?>
			        		<label for="website">Sitio web</label>
			        	</div>
					</div>

				</div>

			</div>
		</div>

		<div id="container-data-company" class="card" style="border-top-width: 3px; border-top-color: #D41C76; border-top-style: solid; display: block;">
			<div class="card-content">
				
				<div class="row">
					<div class="col s12 m12 l12">
						<h5 class="center">Datos de empresa</h5>
					</div>
				</div>

				<div class="row">
					
					<!--<div id="container_name_company">-->
						<div class="input-field col s12 m12 l8">
							<i class="material-icons prefix">store</i>
			          		<?php echo $this->formElement($form->get('name_company')); ?>
			          		<label for="name_company">Nombre de la empresa</label>
			        	</div>
					<!--</div>-->

				</div>

				<div class="row">
					
					<div class="input-field col s12 m12 l4">
						<i class="material-icons prefix">location_on</i>
    					<?php echo $this->formElement($form->get('state_of_mexico')); ?>
    					<?php //echo $form->getElement("state_of_mexico")->setAttrib("disable", array(1)); ?>
    					<label>Estado</label>
  					</div>

  					<div class="input-field col s12 m12 l4">
  						<i class="material-icons prefix">location_on</i>
    					<?php echo $this->formElement($form->get('district')); ?>
    					<label>Delegaci&oacute;n / Municipio</label>
  					</div>

  					<div class="input-field col s12 m12 l4">
  						<i class="material-icons prefix">location_on</i>
    					<?php echo $this->formElement($form->get('neighborhood')); ?>
    					<label>Colonia</label>
  					</div>

				</div>

				<div class="row">

					<div class="input-field col s12 m6 l8">
						<i class="material-icons prefix">streetview</i>
						<?php echo $this->formElement($form->get('street')); ?>
						<label for="street">Calle</label>
					</div>

					<div class="input-field col s6 m3 l2">
			          	<?php echo $this->formElement($form->get('number_exterior')); ?>
			          	<label for="number_exterior">Numero exterior</label>
			        </div>
					
					<div class="input-field col s6 m3 l2">
			          	<?php echo $this->formElement($form->get('postal_code')); ?>
			          	<label for="postal_code">C&oacute;digo Postal</label>
			        </div>

				</div>

				<div class="row">
        			<!--<div class="input-field col s12">
        				<i class="material-icons prefix">assignment</i>
          				<textarea id="company_description" name="company_description" class="materialize-textarea"></textarea>
          				<label for="company_description">Descripción de la empresa</label>
        			</div>-->
					<div class="input-field col s12">
						<i class="material-icons prefix">assignment</i>
			          	<?php echo $this->formElement($form->get('company_description')); ?>
			          	<label for="company_description">Descripci&oacute;n de la empresa</label>
			        </div>
      			</div>

			</div>
		</div>

		<div id="container-data-type-pet" class="card" style="border-top-width: 3px; border-top-color: #D41C76; border-top-style: solid; display: none;">

			<div class="card-content">

				<div class="row">
					<div class="col s12 m12 l12">
						<h5 class="center">Tipo de Mascota</h5>
					</div>
				</div>
				
				<input type="hidden" id="pet_type_checkbox" name="pet_type_checkbox" />

				<div class="row container-checkbox-pet-type">
					<?php foreach($this->pet_type as $key => $type) : ?>
					
						<div class="col s6 m4 l3" style="margin-top: 10px; margin-bottom: 10px;">
							<p class="check_pet_type">
	      						<input type="checkbox" id="<?php echo 'type_' . $type['id']; ?>" name="type_pet[]" value="<?php echo $type['id']; ?>" />
	      						<label for="<?php echo 'type_' . $type['id']; ?>"><?php echo $type['type']; ?></label>
	    					</p>
						</div>
			
					<?php endforeach; ?>
				</div>
	
				<!--<div class="row">

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_dog" name="type_pet[]" value="dog" />
      						<label for="tag_dog">Perro</label>
    					</p>
					</div>

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_cat" name="type_pet[]" value="cat" />
      						<label for="tag_cat">Gato</label>
    					</p>
					</div>

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_fishes" name="type_pet[]" value="fishes" />
      						<label for="tag_fishes">Peces</label>
    					</p>
					</div>

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_birds" name="type_pet[]" value="birds" />
      						<label for="tag_birds">Aves</label>
    					</p>
					</div>

				</div>

				<div class="row">

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_rodents" name="type_pet[]" value="rodents" />
      						<label for="tag_rodents">Roedores</label>
    					</p>
					</div>

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_reptiles" name="type_pet[]" value="reptiles" />
      						<label for="tag_reptiles">Reptiles</label>
    					</p>
					</div>
					
					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_others_pets" name="type_pet[]" value="others" />
      						<label for="tag_others_pets">Otros</label>
    					</p>
					</div>
					
				</div>-->
				
			</div>
			
		</div>

		<div id="container-data-activity-sector" class="card" style="border-top-width: 3px; border-top-color: #D41C76; border-top-style: solid; display: none;">
			<div class="card-content">

				<div class="row">
					<div class="col s12 m12 l12">
						<h5 class="center">Sector de actividad</h5>
					</div>
				</div>
				

				<input type="hidden" id="sector_activity_checkbox" name="sector_activity_checkbox" />

				<div class="row container-checkbox-sector_activity">
					<?php foreach($this->sector_activity as $key => $sector) : ?>
					
						<div class="col s6 m4 l3" style="margin-top: 10px; margin-bottom: 10px;">
							<p class="check_sector_activity">
	      						<input type="checkbox" id="<?php echo 'sector_' . $sector['id']; ?>" name="activity_sector[]" value="<?php echo $sector['id']; ?>" />
	      						<label for="<?php echo 'sector_' . $sector['id']; ?>"><?php echo $sector['sector']; ?></label>
	    					</p>
						</div>
			
					<?php endforeach; ?>
				</div>

				<!--<div class="row">

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_food" name="activity_sector[]" value="food" />
      						<label for="tag_food">Comida</label>
    					</p>
					</div>

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_health" name="activity_sector[]" value="health" />
      						<label for="tag_health">Salud</label>
    					</p>
					</div>

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_beauty" name="activity_sector[]" value="beauty" />
      						<label for="tag_beauty">Belleza</label>
    					</p>
					</div>

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_walk" name="activity_sector[]" value="walk" />
      						<label for="tag_walk">Paseo</label>
    					</p>
					</div>

				</div>

				<div class="row">

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_toys" name="activity_sector[]" value="toys" />
      						<label for="tag_toys">Juguetes</label>
    					</p>
					</div>
					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_contests" name="activity_sector[]" value="contests" />
      						<label for="tag_contests">Concursos</label>
    					</p>
					</div>

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_adoption" name="activity_sector[]" value="adoption" />
      						<label for="tag_adoption">Adopci&oacute;n</label>
    					</p>
					</div>

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_couple" name="activity_sector[]" value="couple" />
      						<label for="tag_couple">Pareja</label>
    					</p>
					</div>

				</div>

				<div class="row">

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_home" name="activity_sector[]" value="home" />
      						<label for="tag_home">Casas</label>
    					</p>
					</div>

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_training" name="activity_sector[]" value="training" />
      						<label for="tag_training">Adiestramiento</label>
    					</p>
					</div>

					<div class="col s12 m3 l3">
						<p>
      						<input type="checkbox" id="tag_others" name="activity_sector[]" value="others" />
      						<label for="tag_others">Otros</label>
    					</p>
					</div>

				</div>-->
				
			</div>
		</div>

		<div id="container-gallery-image" class="card" style="border-top-width: 3px; border-top-color: #D41C76; border-top-style: solid; display: none;">

			<div class="card-content">

				<div class="row">
					<div class="col s12 m12 l12">
						<h5 class="center">Anuncios</h5>
					</div>
				</div>

				<div class="row">
					
					<div class="col s12 m4 l4">

						<div class="targetOuter">
							<div class="targetLayer"></div>
							<img src="https://phppot.com/demo/jquery-ajax-image-upload/photo.png"  class="icon-choose-image" />
							<div class="icon-choose-image" >
							<input name="image_one" id="image_one" type="file" class="inputFile" onChange="showPreview(this);" />
							</div>
						</div>

						<div class="input-field">
			          		<input type="text" id="description_image_one" name="description_image_one" />
			          		<label for="description_image_one">Descripci&oacute;n</label>
			        	</div>
						
					</div>

					<div class="col s12 m4 l4">

						<div class="targetOuter">
							<div class="targetLayer"></div>
							<img src="https://phppot.com/demo/jquery-ajax-image-upload/photo.png"  class="icon-choose-image" />
							<div class="icon-choose-image" >
							<input name="image_two" id="image_two" type="file" class="inputFile" onChange="showPreview(this);" />
							</div>
						</div>

						<div class="input-field">
			          		<input type="text" id="description_image_two" name="description_image_two" />
			          		<label for="description_image_two">Descripci&oacute;n</label>
			        	</div>
						
					</div>

					<div class="col s12 m4 l4">

						<div class="targetOuter">
							<div class="targetLayer"></div>
							<img src="https://phppot.com/demo/jquery-ajax-image-upload/photo.png"  class="icon-choose-image" />
							<div class="icon-choose-image" >
							<input name="image_three" id="image_three" type="file" class="inputFile" onChange="showPreview(this);" />
							</div>
						</div>

						<div class="input-field">
			          		<input type="text" id="description_image_three" name="description_image_three" />
			          		<label for="description_image_three">Descripci&oacute;n</label>
			        	</div>

					</div>

				</div>

				<div class="row">
					
					<div class="col s12 m4 l4">

						<div class="targetOuter">
							<div class="targetLayer"></div>
							<img src="https://phppot.com/demo/jquery-ajax-image-upload/photo.png"  class="icon-choose-image" />
							<div class="icon-choose-image" >
							<input name="image_four" id="image_four" type="file" class="inputFile" onChange="showPreview(this);" />
							</div>
						</div>

						<div class="input-field">
			          		<input type="text" id="description_image_four" name="description_image_four" />
			          		<label for="description_image_four">Descripci&oacute;n</label>
			        	</div>
						
					</div>

					<div class="col s12 m4 l4">

						<div class="targetOuter">
							<div class="targetLayer"></div>
							<img src="https://phppot.com/demo/jquery-ajax-image-upload/photo.png"  class="icon-choose-image" />
							<div class="icon-choose-image" >
							<input name="image_five" id="image_five" type="file" class="inputFile" onChange="showPreview(this);" />
							</div>
						</div>

						<div class="input-field">
			          		<input type="text" id="description_image_five" name="description_image_five" />
			          		<label for="description_image_five">Descripci&oacute;n</label>
			        	</div>
						
					</div>

					<div class="col s12 m4 l4">

						<div class="targetOuter">
							<div class="targetLayer"></div>
							<img src="https://phppot.com/demo/jquery-ajax-image-upload/photo.png"  class="icon-choose-image" />
							<div class="icon-choose-image" >
							<input name="image_six" id="image_six" type="file" class="inputFile" onChange="showPreview(this);" />
							</div>
						</div>

						<div class="input-field">
			          		<input type="text" id="description_image_six" name="description_image_six" />
			          		<label for="description_image_six">Descripci&oacute;n</label>
			        	</div>

					</div>

				</div>

			</div>
			
		</div>

		<div id="container-all-actions" class="card" style="display: block;">
			<div class="card-content">

				<!-- CAMBIAR reCAPTCHA SEGUN EL SERVIDOR QUE SE OCUPA, BASTA CON SOLO CAMBIAR EL data-sitekey
				reCAPTCHA DE AMAZON
	            <div class="g-recaptcha" data-sitekey="6Le-xBsUAAAAAAn9ab236oF31EJ1BK1gXV1-Cijn"></div>

	            reCAPTCHA DE RECUPERA
	            <div class="g-recaptcha" data-sitekey="6LeWVBkUAAAAAG4jSEKadauLuhIvht_EWYjg7Hmb"></div>

	            reCAPTCHA DE LOCAL
	            <div class="g-recaptcha" data-sitekey="6LehDRgUAAAAABvR9cuOWGp4P70goBgn2Q5zbbRG"></div>

                reCAPTCHA DE LOCAL con cuenta cami
	            <div class="g-recaptcha" data-sitekey="6LfPyiMUAAAAAN9GUixh4d3vnGitJSHAJ6QEsc7z"></div> 

				reCAPTCHA DE DESARROLLO PET cuenta expendio
	            <div class="g-recaptcha" data-sitekey="6Le2YlEUAAAAAIqFMo0pUzMDCcXThz8_oVmWUzNL"></div>
	            
	        	-->

	            <div class="row">
					<div class="col s12 m12 l12">
						<div style="width: 302px; margin:auto;" class="g-recaptcha" data-sitekey="6LfPyiMUAAAAAN9GUixh4d3vnGitJSHAJ6QEsc7z"></div>
					</div>
				</div>

				<div class="row">
					<div class="col s12 m12 l12">
						<p class="center">
                        	Al registrarte, aceptas nuestras
                       		<a  href="<?php echo $this->basePath('/Documents/Aviso Legal y Cond de uso Recupera.net.pdf')?>" target="_blank">Condiciones</a>
					    		y nuestra
							<a class="_m4qul" href="<?php echo $this->basePath('/Documents/Política de privacidad Recupera.net.pdf')?>" target="_blank">Política de privacidad</a>.
							<!--<a class="btn btn-success" href="<?php echo $this->basePath('/Documents/Aviso Legal y Cond de uso Recupera.net.pdf')?>"> Descarga </a>-->
						</p>
					</div>
				</div>

				<div class="row">
					<div class="col s12 m12 l12 center">
						<button type="submit" id="btn_register" class="waves-effect waves-light btn-large pink col s12 m6 l6 offset-m3 offset-l3">Reg&iacute;strate ahora</button>
					</div>
				</div>

				<div class="row" style="margin-bottom: 0;">
					<div class="col s12 m12 l12">
						<p class="center-align" style="font-size:25px;">
							¿Ya tienes una cuenta?
							<a href="<?php echo $this->basePath('/auth/login'); ?>">Iniciar sesi&oacute;n</a>
						</p>
					</div>
				</div>
				
			</div>
		</div>

		<?php
		echo $this->form()->closeTag();
		?>

	</div>
</div>

<script src="<?php echo $this->basePath('/pegalinaslive/js/register/company.js'); ?>"></script>
<script src="<?php echo $this->basePath('/pegalinaslive/js/addresses/addresses.js'); ?>"></script>

<script>
// BasePath of project
var $basePath 		= '<?php echo $this->basePath(); ?>';
var $district    	= 0;
var $neighborhood 	= 0;

// Variable para saber en que vista nos encontramos y validar en el archivo js
var currentView 	= "addSupplier"
</script>